### ISSUE TITLE
Frontend pod crashing

### ISSUE THREAD

**Issue by davidpanic** [nrwl/nx-cloud-helm#123]
The frontend pod keeps restarting. The only thing printed in the logs is:

```
{"_cloudMode":"private-enterprise","_logger":"express-handler","_release":"2405.02.15.hotfix6","_service":"remix-server","full_message":"Server closed gracefully","host":"nx-cloud-frontend-7fdb555857-zqd5c","level":6,"short_message":"Server closed gracefully","timestamp":1718367478.176,"version":"1.1"}
```

All of the other pods have started successfully and the api pod reports a successful connection to MongoDB:

```
{"@t":"2024-06-14T11:56:48.251739439Z","@l":"INFO","host":"nx-cloud-nx-api-5bf6cccf88-pbvbs","logger":"io.nrwl.Main","appName":"nx-api","appVersion":"2405.02.15.hotfix6","cloudMode":"private-enterprise","context":"main","@m":"connected to mongodb+srv://****:****@nx-cloud-mongodb-svc.mongodb.svc.cluster.local nrwl-api"}
```

I have tried removing the liveness and readiness probes but the pod is still restarting.

I am using `imageTag: 2405.02.15` which appears to be the latest at the moment.

Here are the complete values that I am using. Ingress is set up manually via a Træfik IngressRoute.

```
global:
  namespace: nx-cloud
  imageTag: 2405.02.15

nxCloudAppURL: https://nx-cloud.[REDACTED].[TLD]
secret:
  name: nx-cloud
  nxCloudMongoServerEndpoint: NX_CLOUD_MONGO_SERVER_ENDPOINT
  adminPassword: ADMIN_PASSWORD
  gitlabAppId: GITLAB_APP_ID
  gitlabAppSecret: GITLAB_APP_SECRET

ingress:
  skip: true

gitlab:
  apiUrl: https://git.[REDACTED].[TLD]
  auth:
    enabled: true
```
