### ISSUE TITLE
Nx-cloud-nx-api giving 'Liveness probe failed: Get "<private_url>:4203/nx-cloud/uptime-check": context deadline exceeded'

### ISSUE THREAD

**Issue by DiogoVCS** [nrwl/nx-cloud-helm#14]
Hi, first of all great repo :+1: 

We are having an issue, we completely deployed everything to Kubernetes successfully, but we are receiving the following error from the nx-cloud-nx-api Pod: `Liveness probe failed: Get "<private_url>:4203/nx-cloud/uptime-check": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`. 
This error causes the pod to be killed and recreated, and therefore when running commands locally we get the error:
 
>  NX   Nx Cloud Problems

   - Error when connecting to Nx Cloud. Code: ECONNABORTED. Error: timeout of 10000ms exceeded.

This basically means that we cannot properly use the NxCloud because it is constantly failing due to this error (because it is failing in every project build and restarting the pod). We can access the NxCloud App URL and it is working fine, but the liveness probe of the nx-cloud-nx-api fails as soon as requests arrive.

We have already tried to increase the timeoutSeconds of the livenessProbe, and still the result is the same.

We are using the mongodb operator for kubernetes and the file-server, also, we have no github/gitlab integrations. We are providing our own ingress. Our values.yaml for the nx-cloud looks like this:

```
image:
  tag: 'latest'
  local: false

nxCloudAppURL: '<ingress_app_url>'
verboseLogging: true
verboseMongoLogging: true

replicas:
  frontend: 1
  api: 1
  nxApi: 1

fileStorage:
  storageClassName: ''
  size: '30Gi'

azure:
  enabled: false
  container: 'nx-cloud'

secret:
  name: 'cloudsecret'
  nxCloudMongoServerEndpoint: 'NX_CLOUD_MONGO_SERVER_ENDPOINT'
  adminPassword: 'ADMIN_PASSWORD'

mode: "private-community"

ingress:
  skip: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Setting size to 0 disables checking of client request body size.
    nginx.ingress.kubernetes.io/proxy-body-size: 0m
  hosts:
    - host: <private_host>
      paths:
        - path: /file
          pathType: Prefix
          backend:
            service:
              name: nx-cloud-file-server-service
              port:
                number: 5000
        - path: /nx-cloud
          pathType: Prefix
          backend:
            service:
              name: nx-cloud-nx-api-service
              port:
                number: 4203
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: nx-cloud-nrwl-api-service
              port:
                number: 4000
        - path: /graphql
          pathType: Prefix
          backend:
            service:
              name: nx-cloud-nrwl-api-service
              port:
                number: 4000
        - path: /auth
          pathType: Prefix
          backend:
            service:
              name: nx-cloud-nrwl-api-service
              port:
                number: 4000
        - path: /download
          pathType: Prefix
          backend:
            service:
              name: nx-cloud-nrwl-api-service
              port:
                number: 4000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nx-cloud-frontend-service
              port:
                number: 8080
  tls:
    - secretName: <secret_name_dev_tls>
      hosts:
        - <private_host>

## DISABLED VALUES:

useCosmosDb: false

awsS3:
  enabled: false

github:
  auth:
    enabled: false
  pr:
    defaultWorkspaceId: ''
    enabled: false
    mode: 'webhook'
    apiUrl: ''

gitlab:
  mr:
    enabled: false
    apiUrl: ''
    projectId: ''
```

Do you guys have any ideia of what we are missing here?
